### ISSUE TITLE
AngularGradient doesn't work with Transparent color

### ISSUE THREAD

**Issue by Shujee** [JohanLarsson/Gu.Wpf.Geometry#16]
It looks like AngularGradient doesn't support Transparent color. Even when StartColor and EndColor are set to **Transparent** and **Red**, the gradient runs from **White** to **Red**. Don't know if this is a bug or what.

**Comment by JohanLarsson** [comment]
Thanks for reporting! Sounds like a bug, I'll try to repro it.

**Comment by JohanLarsson** [comment]
Have a repro in the demo project, dunno how I missed this. Adding UI-test & fix for it.

**Comment by JohanLarsson** [comment]
I'm planning on adding some other things tomorrow, if you are in a hurry I can release it now. If you happen to know HLSL well you can review the diff of the .fx file. The bug was that I did not premultiply alpha correctly.

**Comment by Shujee** [comment]
Thanks a lot. And yes, please take your time; I'm not in a hurry. I'm not an HLSL expert, but was able to fix the issue on my own (though not as cleanly as you have done) after spending several hours doing trial and error.
One more thing. It looks like the **Effects** property of WPF shapes paints on top of their **Stroke** and **Fill**. Thus I can't make an rainbow-colored arc that has a black border around it. Can you update this effect such that it draws border using the standard **Stroke** and **StrokeThickness** properties of the shape?

(I have already done this bordering thing, but the output is not as fine as the regular **Storke** property. It looks a bit pixelated because of the curvature of the arc. I have used the following code:

```
static float4 black = float4(0.0, 0.0, 0.0, 1.0);
float Dist = distance(uv, CenterPoint);
if (f < 0.002 || f > .998 || abs(Dist - R1) < .002 || abs(Dist - R2) < .002)
  return black; 
```
**R1** and **R2** are two **float** properties of the effect, corresponding to the inner and outer radius of the shape.

**Comment by JohanLarsson** [comment]
![angulargradient_startangle_0_centralangle_-270](https://user-images.githubusercontent.com/1640096/33271094-8e732234-d386-11e7-81ad-cc67c277db47.png)

Managed to smooth the edges a bit.
I'm not sure about adding support for borders. Drawing an arc with border only above the arc with the gradient feels easier. Reason I hesitate is it is probably a bit of work and not sure it is general purpose enough. And then we need to come up with an API that is natural to use. You can go ahead and create an issue about it of course.

**Comment by JohanLarsson** [comment]
Published now: https://www.nuget.org/packages/Gu.Wpf.Geometry/2.0.0
