### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by JohanLarsson** [JohanLarsson/Gu.Wpf.Geometry#8]
I'm not a native speaker so would appreciate feedback on naming before publishing a nuget.

- Do you prefer Balloon or Bubble or something better?
- Is BoxBalloon and EllipseBalloon good?
- Should we name the balloon that subclasses `ContentControl` ContentBalloon or is it just dumb redundancy?

Don't hesitate to write anything here.

**Comment by TWolverson** [comment]
At least one framework I am aware of calls this a [balloon tooltip](https://msdn.microsoft.com/en-us/library/windows/desktop/hh298401(v=vs.85).aspx). IMHO this could be taken as precedent. A [speech bubble](https://www.google.co.uk/search?q=speech+bubble&espv=2&biw=1680&bih=949&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiI_NSW3s_LAhVLWxQKHX_SCjoQ_AUIBigB) seems to come in many shapes, but predominantly those other than rounded rectangles.

**Comment by ReedCopsey** [comment]
I'd use balloon.  Drop Content

**Comment by JohanLarsson** [comment]
Thank you my friends, balloon it is. Publishing the nuget.
